CotizacionesFinal2RROAA/Models/Cotizacion.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

/// <summary>
/// Archivo donde se definen las clases del Dominio del problema.
/// </summary>
namespace Cotizaciones.Models
{

    /// <summary>
    /// Clase que representa a una cotizacion en el Sistema.
    /// </summary>
    /// <remarks>
    /// Esta clase pertenece al modelo del Dominio y posee las siguientes restricciones:
    /// - No permite valores null en sus atributos.
    /// </remarks>
    public class Cotizacion
    {

        //atributos de la clase cotización
        public int ID { get; set; }
        public string nombreCliente{get ; set; }
        public string descripcionCotizacion{get; set; }
        public int valorCotizacion{get; set; }
        public string estadoCotizacion{get; set; }
        public DateTime fechaCotizacion {get; set; }
        public DateTime fechaValidez{get; set; }
        public String PersonaRut {get;set; }
        [ForeignKey("PersonaRut")]
        public Persona persona {get; set;}

    }
}

CotizacionesFinal2RROAA/Controllers/CotizacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cotizaciones.Data;
using Cotizaciones.Models;

//Controlador para la clase Cotización
//En este controlador se designa un namespace dentro del cuál se gestionan los elementos ingresados
//manualmente a las vistas con la base de datos del sistema
//
//Se controlan gestión de datos entre vistas del modelo Cotización (Index, create, delete, details, edit) y BD.
// 
namespace Cotizaciones.Controllers
{
    public class CotizacionController : Controller
    {
        private readonly CotizacionesContext _context;

        public CotizacionController(CotizacionesContext context)
        {
            _context = context;
        }

        // GET: Cotizacion
        public async Task<IActionResult> Index()
        {
            var cotizacionesContext = _context.Cotizacion.Include(c => c.persona);
            return View(await cotizacionesContext.ToListAsync());
        }

        // GET: Cotizacion/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cotizacion = await _context.Cotizacion
                .Include(c => c.persona)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (cotizacion == null)
            {
                return NotFound();
            }

            return View(cotizacion);
        }

        // GET: Cotizacion/Create
        public IActionResult Create()
        {
            ViewData["PersonaRut"] = new SelectList(_context.Personas, "Nombre", "Rut");
            return View();
        }

        // POST: Cotizacion/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,nombreCliente,descripcionCotizacion,valorCotizacion,estadoCotizacion,fechaCotizacion,fechaValidez,PersonaRut")] Cotizacion cotizacion)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cotizacion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PersonaRut"] = new SelectList(_context.Personas, "Rut", "Rut", cotizacion.PersonaRut);
            return View(cotizacion);
        }

        // GET: Cotizacion/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cotizacion = await _context.Cotizacion.SingleOrDefaultAsync(m => m.ID == id);
            if (cotizacion == null)
            {
                return NotFound();
            }
            ViewData["PersonaRut"] = new SelectList(_context.Personas, "Rut", "Rut", cotizacion.PersonaRut);
            return View(cotizacion);
        }

        // POST: Cotizacion/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,nombreCliente,descripcionCotizacion,valorCotizacion,estadoCotizacion,fechaCotizacion,fechaValidez,PersonaRut")] Cotizacion cotizacion)
        {
            if (id != cotizacion.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cotizacion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CotizacionExists(cotizacion.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PersonaRut"] = new SelectList(_context.Personas, "Rut", "Rut", cotizacion.PersonaRut);
            return View(cotizacion);
        }

        // GET: Cotizacion/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cotizacion = await _context.Cotizacion
                .Include(c => c.persona)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (cotizacion == null)
            {
                return NotFound();
            }

            return View(cotizacion);
        }

        // POST: Cotizacion/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cotizacion = await _context.Cotizacion.SingleOrDefaultAsync(m => m.ID == id);
            _context.Cotizacion.Remove(cotizacion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CotizacionExists(int id)
        {
            return _context.Cotizacion.Any(e => e.ID == id);
        }
    }
}

CotizacionesFinal2RROAA/Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cotizaciones.Data;
using Cotizaciones.Models;

//Controlador para la clase Persona
//En este controlador se designa un namespace dentro del cuál se gestionan los elementos ingresados
//manualmente a las vistas con la base de datos del sistema
//
//Se controlan gestión de datos entre vistas del modelo Persona (Index, create, delete, details, edit) y BD.
// 

namespace Cotizaciones.Controllers
{
    public class PersonaController : Controller
    {
        private readonly CotizacionesContext _context;

        public PersonaController(CotizacionesContext context)
        {
            _context = context;
        }

        // GET: Persona
        public async Task<IActionResult> Index()
        {
            return View(await _context.Personas.ToListAsync());
        }

        // GET: Persona/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Personas
                .SingleOrDefaultAsync(m => m.Rut == id);
            if (persona == null)
            {
                return NotFound();
            }

            return View(persona);
        }

        // GET: Persona/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Persona/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Rut,Nombre,Paterno,Materno")] Persona persona){
            //var listaPersona = _context.Personas.Where(m => m.Rut == persona.Rut);

            //if(listaPersona == null){
              //  return NotFound();
            //}else
            //{
              //  int cant = listaPersona.Count();
                //if (listaPersona.Count() == 0){
                  //  if (ModelState.IsValid){
                    //        _context.Add(persona);
                      //      await _context.SaveChangesAsync();
                        //    return RedirectToAction(nameof(Index));
                     //}
                   // return View(persona);
               // }else{      
                    //agregar popup de rut ya existe!  
                 //   ModelState.AddModelError("rut", "El Rut ingresado ya existe en el sistema!, intenta con otro Rut.");           
                    //return RedirectToAction(nameof(Create));
                   // return View (persona);
                   //}
            //}

            if (ModelState.IsValid)
            {
                if(Persona.validarRut(persona.Rut)){
                    _context.Add(persona);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                }
                               
            }
            return View(persona);

        }

        // GET: Persona/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Personas.SingleOrDefaultAsync(m => m.Rut == id);
            if (persona == null)
            {
                return NotFound();
            }
            return View(persona);
        }

        // POST: Persona/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Rut,Nombre,Paterno,Materno")] Persona persona)
        {
            if (id != persona.Rut)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(persona);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonaExists(persona.Rut))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(persona);
        }

        // GET: Persona/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Personas
                .SingleOrDefaultAsync(m => m.Rut == id);
            if (persona == null)
            {
                return NotFound();
            }

            return View(persona);
        }

        // POST: Persona/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var persona = await _context.Personas.SingleOrDefaultAsync(m => m.Rut == id);
            _context.Personas.Remove(persona);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonaExists(string id)
        {
            return _context.Personas.Any(e => e.Rut == id);
        }

    }
}

CotizacionesFinal2RROAA/Views/Cotizacion/Create.cshtml
<!--Formulario del model Cotización para agregar una nueva cotización-->

@model Cotizaciones.Models.Cotizacion

@{
    ViewData["Title"] = "Create";
}

<h2>Agregar nueva cotización</h2>

<hr />
<div class="row">
    <div class="col-md-5">
        <form asp-action="Create" onsubmit="validarForm()">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <!--<label asp-for="PersonaRut" class="control-label"></label>-->
                <p><b>Rut cliente: </b></p>
                <select asp-for="nombreCliente" class ="form-control" asp-items="ViewBag.PersonaRut" required
                id="ddlRut" onchange="elegirRutCliente()" >
                    <option value="0">Seleccione RUT</option>
                </select>
            </div>

            <a asp-action="Create" asp-controller="Persona">¿Cliente nuevo?, Agregalo aquí !</a>
            

                <!--NOTA: agregat table-->
            <div class="form-group">
                <br/>
                <!--<label asp-for="nombreCliente" class="control-label"></label>-->
                
                <p><b>Nombre cliente: </b></p>
                <input placeholder="Ingrese nombre " asp-for="PersonaRut" class="form-control" id="cliente"/>
                <span asp-validation-for="nombreCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <!--<label asp-for="descripcionCotizacion" class="control-label"></label>-->
                <p><b>Descripción de cotización: </b></p>
                <textarea placeholder="Ingrese descripción" asp-for="descripcionCotizacion" class="form-control" rows="2" ></textarea>
                <span asp-validation-for="descripcionCotizacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <!--<label asp-for="valorCotizacion" class="control-label"></label>-->
                <p><b>Valor cotización :</b> [ Sin signo $ ni puntos ]</p>
                <input placeholder="Ingrese valor" asp-for="valorCotizacion" class="form-control" />
                <span asp-validation-for="valorCotizacion" class="text-danger"></span>
            </div>

            <div class="form-group">
                <p><b>Estado cotización: </b></p>
                <select class ="form-control" asp-for="estadoCotizacion">
                    <!--<option>Seleccione un estado</option>-->
                    <option>En progreso</option>
                    <option>Completada</option>
                    <option>Cancelada</option>
                </select>
                <span asp-validation-for="estadoCotizacion" class="text-danger"></span>
            </div>

            <div class="form-group">
                <!--<label asp-for="fechaCotizacion" class="control-label"></label>-->
                <p><b>Fecha Cotización: </b></p>
                <input asp-for="fechaCotizacion" class="form-control" />
                <span asp-validation-for="fechaCotizacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <!--<label asp-for="fechaValidez" class="control-label"></label>-->
                <p><b>Fecha de expiración: </b></p>
                <input asp-for="fechaValidez" class="form-control" />
                <span asp-validation-for="fechaValidez" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Crear nueva cotización" class="btn btn-default" />  |  
                <a asp-action="Index">Volver a lista </a>
            </div>
        </form>
    </div>
        <div class="col-md-5">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
       <img align="right" class="center-block" src="/images/nuevac.png" width=40% height=40%> 
    </div>
</div>

<script type="text/javascript">
    function elegirRutCliente(){
        if(ddlRut.value == 0){
            alert("Por favor seleccione un RUT");
        }else{
            document.getElementById("cliente").value = document.getElementById("ddlRut").value;
        }
    }

    function validarForm(){
        var rut = $("#ddlRut>option:selected").html()
        document.getElementById("cliente").value =rut;
    }
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CotizacionesFinal2RROAA/Views/Cotizacion/Delete.cshtml
<!--Formulario del model Cotización para Eliminar una nueva cotización-->

@model Cotizaciones.Models.Cotizacion

@{
    ViewData["Title"] = "Delete";
}

<h2>Eliminar cotización</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombreCliente)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.nombreCliente)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.descripcionCotizacion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.descripcionCotizacion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.valorCotizacion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.valorCotizacion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.estadoCotizacion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.estadoCotizacion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.fechaCotizacion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.fechaCotizacion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.fechaValidez)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.fechaValidez)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.persona)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.persona.Rut)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Eliminar cotización" class="btn btn-default" /> |
        <a asp-action="Index">Volver a lista de cotizaciones</a>
    </form>
</div>

CotizacionesFinal2RROAA/Views/Cotizacion/Details.cshtml
<!--Formulario del model Cotización para desplegar detalle de una cotización-->

@model Cotizaciones.Models.Cotizacion

@{
    ViewData["Title"] = "Details";
}

<br>


<style>
table, th, td {
    border: 1px solid black;
}
th, td {
    padding: 15px;
}
</style>
<br>



<table style="width:100%" >
  <tr>
    <th colspan="3"><h1 style="text-align:center">Detalle de Cotizacion</h1></th>
  </tr>

  <tr>
    <th colspan="3" style="text-align:left"><b>Fecha Cotización :</b> @Html.DisplayFor(model => model.fechaCotizacion)</th>
  </tr>

  <tr>
    <th colspan="3" style="text-align:left"><b>Fecha Validez:</b> @Html.DisplayFor(model => model.fechaValidez)</th>
  </tr>

  <tr>
      <td><b>Rut Cliente : @Html.DisplayFor(model => model.persona.Rut)</b></td>
    <td><b>Nombre Cliente : @Html.DisplayFor(model => model.nombreCliente)</b></td> 
    <td><b>Estado Cotización : @Html.DisplayFor(model => model.estadoCotizacion)</b></td>
  </tr>


  <tr>
    <th colspan="3"><b>Detalle Cotización: @Html.DisplayFor(model => model.descripcionCotizacion)</b></th>
  </tr>

  <tr>
    <th colspan="3" style="text-align:right"><b>Valor : $ @Html.DisplayFor(model => model.valorCotizacion) CLP</b></th>
  </tr

   <tr>
  </tr>
  

</table>
<br>
<br>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Editar cotizacion</a> |
    <a asp-action="Index">Volver a lista de cotizaciones</a>
</div>

CotizacionesFinal2RROAA/Views/Cotizacion/Edit.cshtml
<!--Formulario del model Cotización para editar una nueva cotización-->

@model Cotizaciones.Models.Cotizacion

@{
    ViewData["Title"] = "Edit";
}

<h2>Editar cotización</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="nombreCliente" class="control-label"></label>
                <input asp-for="nombreCliente" class="form-control" />
                <span asp-validation-for="nombreCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descripcionCotizacion" class="control-label"></label>
                <input asp-for="descripcionCotizacion" class="form-control" />
                <span asp-validation-for="descripcionCotizacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="valorCotizacion" class="control-label"></label>
                <input asp-for="valorCotizacion" class="form-control" />
                <span asp-validation-for="valorCotizacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="estadoCotizacion" class="control-label"></label>
                <input asp-for="estadoCotizacion" class="form-control" />
                <span asp-validation-for="estadoCotizacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fechaCotizacion" class="control-label"></label>
                <input asp-for="fechaCotizacion" class="form-control" />
                <span asp-validation-for="fechaCotizacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fechaValidez" class="control-label"></label>
                <input asp-for="fechaValidez" class="form-control" />
                <span asp-validation-for="fechaValidez" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonaRut" class="control-label"></label>
                <select asp-for="PersonaRut" class="form-control" asp-items="ViewBag.PersonaRut"></select>
                <span asp-validation-for="PersonaRut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar cambios" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a lista de cotizaciones</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CotizacionesFinal2RROAA/Views/Cotizacion/Index.cshtml
<!--Formulario index del model Cotización para desplegar la lista de las cotizaciones actuales-->
<!--y las acciones a realizar sobre esta-->

@model IEnumerable<Cotizaciones.Models.Cotizacion>

@{
    ViewData["Title"] = "Index";
}

<h1>Gestión de cotizaciones</h1>
<hr>
<p>
    <a asp-action="Create">Agregar nueva cotización</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    <!--@Html.DisplayNameFor(model => model.nombreCliente)-->
                    Nombre Cliente
                </th>
                <th>
                    <!-- @Html.DisplayNameFor(model => model.persona) -->
                    Rut Cliente
                </th>
                <th>
                    <!-- @Html.DisplayNameFor(model => model.fechaCotizacion) -->
                    Fecha Cotización
                </th>
                <th>
                    <!-- @Html.DisplayNameFor(model => model.fechaValidez) -->
                    Fecha Validez
                </th>
                <th>
                    <!-- @Html.DisplayNameFor(model => model.estadoCotizacion) -->
                    Estado Cotización
                </th>
                <th>
                    <!--@Html.DisplayNameFor(model => model.descripcionCotizacion)-->
                    Descripción 
                </th>
                <th>
                    <!--@Html.DisplayNameFor(model => model.valorCotizacion)-->
                    Valor
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nombreCliente) 
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.persona.Rut)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fechaCotizacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fechaValidez)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.estadoCotizacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descripcionCotizacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.valorCotizacion)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>

CotizacionesFinal2RROAA/Views/Cotizacion/PreCreate.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<br>
<h1><b>Generar cotización para:</b></h1>
<br>
<div class="row"><center>
    <div class="col-md-3">
        <h2><b>Nuevo cliente</b></h2>
        <ul>
            <a href='@Url.Action("Create", "Persona")'>
                <img class="center-block" src="/images/nuevo.png" width=100% height=100%>    
            </a>
        </ul>
    </div>
        <div class="col-md-3">
        <h2></h2>
        <ul>
            
        </ul>
    </div>
    <div class="col-md-3">
        <h2><b>Cliente existente</b></h2>
        <ul>
            <a href='@Url.Action("Create", "Cotizacion")'>
            <img class="center-block" src="/images/antiguo.png" width=100% height=100% >
            </a> 
        </ul>
    </div>
    <div class="col-md-3">
        <h2></h2>
        <ul>
            
        </ul>
    </div>
    </center>
</div>